# Generated by Django 4.2.4 on 2023-08-21 20:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NavApps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "img",
                    models.FileField(
                        blank=True, default=None, null=True, upload_to="static/images"
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Apps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Folder", "Folder"),
                            ("File", "File"),
                            ("App", "App"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "img",
                    models.ImageField(blank=True, null=True, upload_to="static/images"),
                ),
                ("content", models.TextField(blank=True, null=True)),
                (
                    "app",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laurentiumarian.navapps",
                    ),
                ),
            ],
        ),
    ]
