# Generated by Django 4.2.4 on 2023-08-19 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("laurentiumarian", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Apps",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("Folder", "Folder"),
                            ("File", "File"),
                            ("App", "App"),
                        ],
                        max_length=100,
                    ),
                ),
                ("img", models.ImageField(blank=True, null=True, upload_to="images/")),
                (
                    "app",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="laurentiumarian.navapps",
                    ),
                ),
            ],
        ),
    ]
