# Generated by Django 4.2.4 on 2023-08-19 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("laurentiumarian", "0002_apps"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apps",
            name="app",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="laurentiumarian.navapps",
            ),
        ),
    ]
