# Generated by Django 4.2.4 on 2023-08-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laurentiumarian", "0002_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="description",
            name="code",
            field=models.TextField(blank=True, null=True),
        ),
    ]
