# Generated by Django 4.2.4 on 2023-08-19 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laurentiumarian", "0003_alter_apps_app"),
    ]

    operations = [
        migrations.AddField(
            model_name="apps",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
