# Generated by Django 4.2.4 on 2023-08-20 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laurentiumarian", "0004_apps_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apps",
            name="img",
            field=models.ImageField(blank=True, null=True, upload_to="static/images"),
        ),
    ]
